import type { Vector } from "~/utils/quizzes/country/countries";

export const usStateVectorOverrides: Record<string, Partial<Vector>> = {
    "countries.usa.al": { climate_warm: 2, climate_seasons: 1, climate_heat_ok: 2, nature_water: 2, nature_mountains_forest: 1, metro_midcity: 2, metro_smalltown: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.ak": { climate_cold: 3, climate_cold_ok: 3, nature_mountains_forest: 3, nature_water: 2, nature_diversity_need: 2, metro_smalltown: 3, transport_car: 2, isolation_ok: 2, country_large: 3 },
    "countries.usa.az": { climate_warm: 2, climate_heat_ok: 3, nature_mountains_forest: 1, nature_water: 0, nature_diversity_need: 1, metro_midcity: 2, metro_smalltown: 1, transport_car: 3, city_sprawl: 3 },
    "countries.usa.ar": { climate_seasons: 2, climate_warm: 1, climate_heat_ok: 2, nature_mountains_forest: 2, nature_water: 1, metro_smalltown: 2, metro_midcity: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.ca": { climate_warm: 2, climate_seasons: 1, climate_heat_ok: 2, nature_water: 3, nature_mountains_forest: 2, nature_diversity_need: 3, metro_megacity: 2, metro_midcity: 2, transport_car: 2, transport_public: 2, city_sprawl: 2, city_vertical: 2, country_large: 3 },
    "countries.usa.co": { climate_seasons: 2, climate_cold_ok: 2, nature_mountains_forest: 3, nature_water: 1, nature_diversity_need: 2, metro_midcity: 2, metro_smalltown: 1, transport_car: 2 },
    "countries.usa.ct": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 2, nature_mountains_forest: 1, metro_midcity: 2, transport_public: 2, transport_car: 2, city_vertical: 1 },
    "countries.usa.de": { climate_seasons: 2, climate_warm: 1, nature_water: 3, nature_mountains_forest: 0, metro_midcity: 2, transport_car: 2, transport_public: 1, city_sprawl: 2 },
    "countries.usa.fl": { climate_warm: 3, climate_heat_ok: 3, nature_water: 3, nature_mountains_forest: 0, metro_midcity: 3, transport_car: 3, city_sprawl: 3 },
    "countries.usa.ga": { climate_warm: 2, climate_seasons: 1, climate_heat_ok: 2, nature_mountains_forest: 1, nature_water: 1, metro_midcity: 3, transport_car: 3, city_sprawl: 3 },
    "countries.usa.hi": { climate_warm: 3, climate_heat_ok: 2, nature_water: 3, nature_mountains_forest: 2, nature_diversity_need: 2, geo_island: 3, metro_midcity: 2, metro_smalltown: 1, transport_car: 2, isolation_ok: 2 },
    "countries.usa.id": { climate_seasons: 2, climate_cold_ok: 2, nature_mountains_forest: 3, nature_water: 1, metro_smalltown: 3, transport_car: 3 },
    "countries.usa.il": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 2, nature_mountains_forest: 0, metro_megacity: 2, metro_midcity: 1, transport_public: 2, transport_car: 2, city_vertical: 2 },
    "countries.usa.in": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 1, nature_mountains_forest: 0, metro_midcity: 2, metro_smalltown: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.ia": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 1, nature_mountains_forest: 0, metro_smalltown: 2, metro_midcity: 1, transport_car: 3 },
    "countries.usa.ks": { climate_seasons: 3, climate_heat_ok: 1, climate_cold_ok: 1, nature_water: 0, nature_mountains_forest: 0, metro_smalltown: 2, metro_midcity: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.ky": { climate_seasons: 2, climate_warm: 1, nature_mountains_forest: 2, nature_water: 1, metro_smalltown: 2, metro_midcity: 1, transport_car: 3 },
    "countries.usa.la": { climate_warm: 3, climate_heat_ok: 3, nature_water: 3, nature_mountains_forest: 0, metro_midcity: 2, transport_car: 3, city_sprawl: 2 },
    "countries.usa.me": { climate_cold: 2, climate_seasons: 2, climate_cold_ok: 2, nature_water: 3, nature_mountains_forest: 3, metro_smalltown: 3, transport_car: 3 },
    "countries.usa.md": { climate_seasons: 2, climate_warm: 1, nature_water: 2, nature_mountains_forest: 1, metro_megacity: 1, metro_midcity: 2, transport_public: 2, transport_car: 2, city_sprawl: 2 },
    "countries.usa.ma": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 3, nature_mountains_forest: 1, metro_megacity: 2, transport_public: 3, transport_car: 1, city_vertical: 2 },
    "countries.usa.mi": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 3, nature_mountains_forest: 1, metro_midcity: 2, metro_smalltown: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.mn": { climate_cold: 2, climate_seasons: 2, climate_cold_ok: 3, nature_water: 2, nature_mountains_forest: 1, metro_midcity: 2, metro_smalltown: 1, transport_car: 2 },
    "countries.usa.ms": { climate_warm: 2, climate_seasons: 1, climate_heat_ok: 2, nature_water: 2, nature_mountains_forest: 0, metro_smalltown: 2, metro_midcity: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.mo": { climate_seasons: 3, climate_heat_ok: 1, climate_cold_ok: 1, nature_water: 1, nature_mountains_forest: 1, metro_midcity: 2, metro_smalltown: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.mt": { climate_cold: 2, climate_seasons: 2, climate_cold_ok: 2, nature_mountains_forest: 3, nature_water: 1, metro_smalltown: 3, transport_car: 3, isolation_ok: 1 },
    "countries.usa.ne": { climate_seasons: 3, climate_cold_ok: 1, climate_heat_ok: 1, nature_water: 0, nature_mountains_forest: 0, metro_smalltown: 2, metro_midcity: 1, transport_car: 3 },
    "countries.usa.nv": { climate_warm: 2, climate_heat_ok: 3, nature_mountains_forest: 1, nature_water: 0, metro_midcity: 2, transport_car: 3, city_sprawl: 3 },
    "countries.usa.nh": { climate_seasons: 3, climate_cold_ok: 2, nature_mountains_forest: 2, nature_water: 2, metro_smalltown: 3, transport_car: 2 },
    "countries.usa.nj": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 2, nature_mountains_forest: 0, metro_megacity: 2, metro_midcity: 1, transport_public: 3, transport_car: 1, city_vertical: 2 },
    "countries.usa.nm": { climate_warm: 2, climate_heat_ok: 2, climate_seasons: 1, nature_mountains_forest: 2, nature_water: 0, nature_diversity_need: 2, metro_smalltown: 2, metro_midcity: 1, transport_car: 3 },
    "countries.usa.ny": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 3, nature_mountains_forest: 1, metro_megacity: 3, transport_public: 3, transport_car: 1, city_vertical: 3 },
    "countries.usa.nc": { climate_seasons: 2, climate_warm: 1, climate_heat_ok: 1, nature_water: 2, nature_mountains_forest: 2, nature_diversity_need: 2, metro_midcity: 2, metro_smalltown: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.nd": { climate_cold: 2, climate_seasons: 2, climate_cold_ok: 2, nature_water: 1, nature_mountains_forest: 0, metro_smalltown: 3, transport_car: 3 },
    "countries.usa.oh": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 1, nature_mountains_forest: 0, metro_midcity: 2, metro_smalltown: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.ok": { climate_seasons: 2, climate_warm: 1, climate_heat_ok: 2, nature_water: 0, nature_mountains_forest: 0, metro_smalltown: 2, metro_midcity: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.or": { climate_seasons: 2, climate_cold_ok: 1, nature_water: 3, nature_mountains_forest: 3, nature_diversity_need: 2, metro_midcity: 2, metro_smalltown: 1, transport_car: 2, transport_public: 1 },
    "countries.usa.pa": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 1, nature_mountains_forest: 1, metro_midcity: 2, metro_megacity: 1, transport_car: 2, transport_public: 1, city_sprawl: 2 },
    "countries.usa.ri": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 3, nature_mountains_forest: 0, metro_midcity: 2, transport_public: 2, transport_car: 1, city_vertical: 1 },
    "countries.usa.sc": { climate_warm: 2, climate_seasons: 1, climate_heat_ok: 2, nature_water: 3, nature_mountains_forest: 1, metro_midcity: 1, metro_smalltown: 2, transport_car: 3, city_sprawl: 2 },
    "countries.usa.sd": { climate_seasons: 2, climate_cold_ok: 1, nature_water: 1, nature_mountains_forest: 1, metro_smalltown: 3, transport_car: 3 },
    "countries.usa.tn": { climate_seasons: 2, climate_warm: 1, climate_heat_ok: 2, nature_mountains_forest: 2, nature_water: 1, metro_midcity: 2, metro_smalltown: 1, transport_car: 3, city_sprawl: 2 },
    "countries.usa.tx": { climate_warm: 2, climate_heat_ok: 3, climate_seasons: 1, nature_water: 1, nature_mountains_forest: 1, nature_diversity_need: 2, metro_megacity: 1, metro_midcity: 3, transport_car: 3, city_sprawl: 3, country_large: 3 },
    "countries.usa.ut": { climate_seasons: 2, climate_cold_ok: 2, nature_mountains_forest: 3, nature_water: 1, metro_midcity: 1, metro_smalltown: 2, transport_car: 3 },
    "countries.usa.vt": { climate_cold: 1, climate_seasons: 3, climate_cold_ok: 2, nature_mountains_forest: 3, nature_water: 1, metro_smalltown: 3, transport_car: 2 },
    "countries.usa.va": { climate_seasons: 2, climate_warm: 1, nature_water: 2, nature_mountains_forest: 2, metro_megacity: 1, metro_midcity: 2, transport_public: 2, transport_car: 2, city_sprawl: 2 },
    "countries.usa.wa": { climate_seasons: 2, climate_cold_ok: 1, nature_water: 3, nature_mountains_forest: 3, nature_diversity_need: 2, metro_midcity: 2, transport_public: 2, transport_car: 1 },
    "countries.usa.wv": { climate_seasons: 3, climate_cold_ok: 2, nature_mountains_forest: 3, nature_water: 1, metro_smalltown: 3, transport_car: 3 },
    "countries.usa.wi": { climate_seasons: 3, climate_cold_ok: 2, nature_water: 2, nature_mountains_forest: 1, metro_midcity: 1, metro_smalltown: 2, transport_car: 3 },
    "countries.usa.wy": { climate_cold: 1, climate_seasons: 2, climate_cold_ok: 2, nature_mountains_forest: 3, nature_water: 1, metro_smalltown: 3, transport_car: 3, isolation_ok: 1 },
    // DC:
    "countries.usa.dc": { climate_seasons: 2, climate_warm: 1, nature_water: 1, nature_mountains_forest: 0, metro_megacity: 2, transport_public: 3, transport_car: 0, city_vertical: 3, nature_city_first: 3 },
};