name: Validate GitHub Actions Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Validate GitHub Actions
        uses: jazzsequence/github-action-validator@v1
        with:
          path-to-workflows: .github/workflows/*.yml
          show-ascii-art: false
